<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "indicadores_carrusel"
 *
 * Auto generated by Extension Builder 2020-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Carrusel de Indicadores Estadisticos',
    'description' => 'Extension para mostrar de forma graficia indicadores estadisticos de la UN',
    'category' => 'plugin',
    'author' => 'Camilo Neiva',
    'author_email' => 'jcneivaa@unal.edu.co ',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
